#!/bin/bash

echo "📝 n8n Setup Instructions"
echo ""
echo "n8n is not currently running. To enable automated soft moderation:"
echo ""
echo "Option 1: Install n8n locally"
echo "  npm install -g n8n"
echo "  n8n start"
echo ""
echo "Option 2: Use Docker"
echo "  docker run -d -p 5678:5678 --name n8n n8nio/n8n"
echo ""
echo "Option 3: Skip n8n (use webhook-only automation)"
echo "  The webhook function now includes MCP analysis and auto-approval"
echo "  n8n provides batch processing every 5 minutes as backup"
echo ""
echo "✅ For now, webhook-based automation is active without n8n"
echo "   Messages with risk < 0.3 are auto-approved instantly"
