#!/bin/bash

echo "🚀 UNAMI MOMENTS PRODUCTION SETUP"
echo "=================================="

echo -e "\n1. 🔐 SUPERADMIN SETUP REQUIRED"
echo "==============================="
echo "The admin dashboard shows 401 Unauthorized because no superadmin exists."
echo ""
echo "MANUAL STEPS REQUIRED:"
echo "1. Go to Supabase SQL Editor: https://app.supabase.com/project/arqeiadudzwbmzdhqkit/sql"
echo "2. Execute this SQL:"
echo ""
echo "-- Create admin_roles table and superadmin user"
echo "CREATE TABLE IF NOT EXISTS admin_roles ("
echo "  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,"
echo "  user_id UUID NOT NULL UNIQUE,"
echo "  role TEXT NOT NULL CHECK (role IN ('superadmin', 'content_admin', 'moderator', 'viewer')),"
echo "  created_at TIMESTAMPTZ DEFAULT NOW()"
echo ");"
echo ""
echo "INSERT INTO admin_roles (user_id, role)"
echo "VALUES ('00000000-0000-0000-0000-000000000000', 'superadmin')"
echo "ON CONFLICT (user_id) DO UPDATE SET role = EXCLUDED.role;"
echo ""
echo "3. Verify with: SELECT * FROM admin_roles WHERE role = 'superadmin';"
echo ""

echo -e "\n2. 🌐 DEPLOYMENT STATUS"
echo "======================"
echo "✅ Vercel (Landing): https://moments.unamifoundation.org"
echo "✅ Railway (Admin/API): https://moments-api.unamifoundation.org"
echo "✅ WhatsApp API: +27 65 829 5041"
echo ""

echo -e "\n3. 🔧 CURRENT ISSUES RESOLVED"
echo "============================"
echo "✅ Fixed Vercel 500 serverless function errors"
echo "✅ Added proper admin-dashboard.html redirects"
echo "✅ Separated landing page (Vercel) from admin (Railway)"
echo "⚠️  PENDING: Superadmin user creation in Supabase"
echo ""

echo -e "\n4. 📋 NEXT STEPS"
echo "==============="
echo "1. Create superadmin user in Supabase (see SQL above)"
echo "2. Test admin access: https://moments-api.unamifoundation.org/admin-dashboard.html"
echo "3. Verify WhatsApp webhook: https://moments-api.unamifoundation.org/health"
echo "4. Test community join: https://wa.me/27658295041?text=START"
echo ""

echo -e "\n5. 🎯 ADMIN DASHBOARD ACCESS"
echo "==========================="
echo "URL: https://moments-api.unamifoundation.org/admin-dashboard.html"
echo "Login: Use any email/password (JWT-based auth)"
echo "Note: Will show 401 until superadmin user is created"
echo ""

echo "✅ Setup script complete. Execute the Supabase SQL to enable admin access."